### ISSUE TITLE
Pas op met @import in CSS

### ISSUE THREAD

**Issue by KrijnHoetmer** [MokhtarAkle/the-startup-responsive-interactieve-website#4]
Een `<link>` tag in je HTML werkt waarschijnlijk beter.

https://github.com/MokhtarAkle/the-startup-responsive-interactieve-website/blob/331b2ec94230eee15ade39749701e06163dc62a4/styles/style.css#L1

**Comment by MokhtarAkle** [comment]
verandert naar link
